# Generated by Django 4.0.5 on 2022-06-08 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_category_alter_product_description_product_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productinstance',
            options={'permissions': (('can_mark_returned', 'Set book as returned'), ('staff_member_required', 'Set user as employee'))},
        ),
    ]
