# Generated by Django 4.0.5 on 2022-06-09 12:15

from django.db import migrations, models
import django.views.generic.list


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_alter_category_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductListView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            bases=(models.Model, django.views.generic.list.ListView),
        ),
        migrations.AddField(
            model_name='productinstance',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
